### ISSUE TITLE
Syntax Highlighting - Doc Tags

### ISSUE THREAD

**Issue by Romanulus** [jrebs/dotfiles#1]
Something like this:

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

Will break the highlighting due to the leading slashes after the @param, @return, etc.

**Comment by jrebs** [comment]
Not my package. It's already a reported bug at https://github.com/StanAngeloff/php.vim/issues/57
